shadow = true;
unredir-if-possible = false;
blur-background = false;
shadow-radius = 2;
shadow-color = "#000000";
shadow-offset-x = 1;
shadow-offset-y = 1;
fading = true;
fade-in-step = 0.02;
fade-out-step = 0.02;
frame-opacity = 1.0;
corner-radius = 8;
blur-kern = "3x3box";
backend = "glx";
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = false;
log-level = "warn";
rules: ({
  match = "class_i = 'ghostty' && focused";
  opacity = 1.0;
}, {
  match = "class_i = 'ghostty' && !focused";
  opacity = 0.8;
}, {
  match = "class_g = 'zen'";
  shadow = false;
  blur-background = false;
},
{
  match = "class_g = 'dwm'";
  corner-radius = 1;
  shadow = false;
},
{
  match = "window_type = 'dropdown_menu' || window_type = 'popup_menu' || window_type = 'utility' || window_type = 'menu'";
  shadow = false;
  opacity = 1.0;
},
);
xrender-sync-fence = true;
show-all-xerrors = true;
use-ewmh-active-win = false;
detect-client-leader = false;
no-fading-destroyed-argb = false;
vsync-use-glfinish = false;
shadow-opacity = 0.3;
fade-delta = 2;
